# -*- coding: utf-8 -*-
"""BulychevaEV_DZ13_Tema14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8M8Sw-E5weLJh4pS4j8PM3GBRZm7Nhr
"""

!pip install requests

from google.colab import files
uploaded = files.upload()

api_key = "dcca36ff37e6d8500be852581205482b7ee67821653805ee404b3fee05030fa6"

import hashlib
import requests
import json

# Загруженный файл
filename = list(uploaded.keys())[0]

# Генерация SHA-256 хэша загруженного файла
with open(filename, "rb") as f:
    file_bytes = f.read()  # Читаем содержимое файла
    sha256_hash = hashlib.sha256(file_bytes).hexdigest()

print(f"Сформированный SHA-256 хэш файла: {sha256_hash}")

# Обращаемся к API VirusTotal
url = f"https://www.virustotal.com/api/v3/files/{sha256_hash}"
headers = {"x-apikey": api_key}

try:
    response = requests.get(url, headers=headers)
    response.raise_for_status()  # Проверяем успешность запроса
except requests.RequestException as e:
    print(f"Произошла ошибка при выполнении запроса: {e}")
else:
    result_json = response.json()
    print("\nПолный JSON-ответ:")
    print(json.dumps(result_json, indent=4))  # Красиво выводим JSON

output_filename = "scan_result.json"

with open(output_filename, "w") as outfile:
    json.dump(result_json, outfile, indent=4)